sudo: false
language: node_js
node_js:
  - 18 # use nodejs v18 LTS
cache: npm
branches:
  only:
    - main # build master branch only
script:
  - npm run build # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  local_dir: dist
  on:
    branch: main
  local-dir: public